/* Auto-generated by libinteractive. Do not edit. */

long long measureBacteria(int gene1, int gene2);
void report(int K, int kind[], long long idx[]);
void tryScience(int T, int C, int cost[], int gene1[], int gene2[]);